workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 120
    environment:
      node: 18
      android: latest
      java: 17
    scripts:
      - name: Install Dependencies
        script: yarn install  # Or use `npm install`

      - name: Build APK
        script: cd android && ./gradlew assembleRelease

      - name: Build AAB
        script: cd android && ./gradlew bundleRelease

      - name: Move Artifacts
        script: |
          mv android/app/build/outputs/apk/release/app-release.apk $CM_BUILD_OUTPUT_DIR/
          mv android/app/build/outputs/bundle/release/app-release.aab $CM_BUILD_OUTPUT_DIR/

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_JSON
        track: production
