workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 120
    environment:
      vars:
        NODE_VERSION: 18
        JAVA_VERSION: 17
    scripts:
      - name: Install Dependencies
        script: |
          yarn install  # Use `npm install` if using npm

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Build AAB
        script: |
          cd android
          ./gradlew bundleRelease

      - name: Move Artifacts
        script: |
          mv android/app/build/outputs/apk/release/app-release.apk $CM_BUILD_OUTPUT_DIR/
          mv android/app/build/outputs/bundle/release/app-release.aab $CM_BUILD_OUTPUT_DIR/

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_JSON
        track: production
